config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:index, :show, :edit, :update, :destroy, :create]
  resources :users, only: [:index, :show, :edit, :update, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  has_one_attached :image
  belongs_to :user

  validates :body, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/nimage.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'nimage.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!


  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def show
    @Book = Book.new
    @book = Book.find(params[:id])
    @users = @book.user
  end

  def edit
    @book = Book.find(params[:id])

  if @book.user.id != current_user.id
    redirect_to books_path
    else
    render :edit
  end

  end


  def create
    @book = Book.new(book_params)
    @users = @book.user
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @user = @book.user
      @books = Book.all
     render :index
    end
  end


  def update
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
      @users = @book.user
      @books = Book.all
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


    def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!


  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
      @books = Book.all
     redirect_to books_path
    end
  end


  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.all
  end



  def edit
  @user = User.find(params[:id])

  if @user.id != current_user.id
  redirect_to user_path(current_user)
  else
    render :edit
  end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(current_user.id)
    else
      @users = User.all
      render :edit
    end
  end


  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>New book</h2>

<%= form_with model: book do |f| %>
 <div class= "a">
  <div class= "b">
    Title
  <div class="form-group">
    <%= f.text_field :title %>
   </div>
  </div>
  <div class= "b">
    Opinion
  <div class="form-group">
    <%= f.text_area :body %>
   </div>
  </div>

  <div class="form-group">
  <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>



<%= form_with model: @book do |f| %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

    <div class="form-group">
      <label for="inputTitle">Title</label><br>
      <%= f.text_field :title %>
    </div>

    <div class="form-group">
    <a>Opinion</a><br>
    <%= f.text_area :body %>
    </div>

    <div class="form-group">
    <%= f.submit 'Update Book', class:"btn btn-success" %>
    </div>

    <%= link_to "Show", book_path(@book.id) %>
    <%= "|"%>
    <%= link_to "Back", books_path %>

    </div>
  </div>
<% end %>
</div>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>


<div class="container px-5 px-sm-0">

  <div class="row">
   <div class="col-md-3">

  <%= render 'users/info', user: @user %>
  <%= render 'list', book: @book %>
  </div>


<div class="col-md-8 offset-md-1">
   <h2>Books</h2>

<table class="table table-hover table-inverse">
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
    </thead>

<% @books.each do |book| %>
  <tbody>
    <tr>
    <th><%= link_to user_path(book.user.id) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %>
      </th>
    <td><%= link_to book_path(book.id) do %>
        <%= book.title%>
      <% end %>
      </td>
      <td><%= book.body%></td>
    </tr>
  </tbody>
<% end %>
</table>
</div>


 </div>
</div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>


<div class="container px-5 px-sm-0">

  <div class="row">
   <div class="col-md-3">


  <%= render 'users/info', user: @users %>
  <%= render 'list', book: @Book %>
  </div>


<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
　　<tbody><tr>

    <td>
    <%= link_to user_path(@book.user.id) do %>
        <%= image_tag @book.user.get_profile_image(100,100) %><br>
    <% end %>
    <%=link_to @book.user.name, user_path(@book.user.id) %></th>
    </td>

    <td><%=link_to @book.title, book_path %></td>
    <td><%= @book.body%></td>
    <% if @book.user == current_user %>
    <td><%= link_to "Edit", "/books/#{@book.id}/edit", class:"btn btn-success"%></td>
    <td><%= link_to "Destroy", "/books/#{@book.id}", method: :delete, class:"btn btn-danger", "data-confirm" => "本当に消しますか？"%>
    <% end %>
    </td>
　　　</tr></tbody>
　　</table>
　</div>
　</div>
</div>

app/views/homes/about.html.erb
<main>
<p id="notice"></p>
 <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !</h1>
   </div>
  </div>
 </div>
</main>

app/views/homes/top.html.erb
<main>
<div>
  <%= flash[:notice] %>
</div>

 <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
       <i class="fas fa-book"></i>
       <strong>Bookers</strong>
         !!</h1>
    <p>In
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
    ,</p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>

    </div>
  </div>
 </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">

      <a class="navbar-brand" href="/">
      <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
        <i class="fas fa-home"></i>
        Home
        <% end %>
      </li>
      <li>
       <%= link_to users_path, class:"nav-link text-light" do %>
        <i class="fas fa-users"></i>
        Users
       <% end %>
      </li>
      <li>
      <%= link_to books_path, class:"nav-link text-light" do %>
        <i class="fas fa-book-open"></i>
        Books
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>
        Log out
        <% end %>
      </li>

    <% else %>
      <li>
      <%= link_to root_path, class:"nav-link text-light" do %>
        <i class="fas fa-home"></i>
        Home
        <% end %>
      </li>
      <li>
      <%= link_to about_path, class:"nav-link text-light" do %>
        <i class="fas fa-link"></i>
        About
      <% end %>
      </li>
      <li>
      <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
        <i class="fas fa-user-plus"></i>
        Sign up
        <% end %>
      </li>
      <li>
      <%= link_to user_session_path, class:"nav-link text-light" do %>
        <i class="fas fa-sign-in-alt"></i>
        Log in
       <% end %>
      </li>
    <% end %>
      </ul>
      </div>
     </div>
    </nav>
  </header>
    <%= yield %>
  </body>

  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

</html>

app/views/users/_info.html.erb
     <h2>User info</h2>
      <th><%= image_tag user.get_profile_image(100,100) %></th>
     <table class="table">
     <tbody>
      <tr>
	     <th>name</th>
       <th><%= user.name %></th>
      </tr>
      <tr>
	     <th>introduction</th>
	     <th><%= user.introduction %></th>
       </tr>
     </tbody>
     </table>

  <div class="row">

    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
     <i class="fas fa-user-cog"></i>
     <% end %>
  </div>

app/views/users/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

  <% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>


<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

<%= form_with model: @user do |f| %>
  <div class="form-group">
    <label for="inputName">Name</label><br>
    <a><%= f.text_field :name %></a>
  </div>

  <div class="form-group">
  <label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, accept: "image/*" %>
  </div>

  <div class="form-group">
  <label for="inputIntroduction">Introduction</label><br>
  <%= f.text_area :introduction %>
  </div>

  <%= f.submit "Update User", class:"btn btn-secondary"%>

<% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
  <div class="col-md-3">

  <%= render 'info', user: @user %>
  <%= render 'books/list', book: @book %>
</div>

<div class="col-md-8 offset-md-1">
   <h2>Users</h2>

<table class="table table-hover table-inverse">
 <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tbody>
    <tr>
      <td>
      <%= image_tag user.get_profile_image(100,100) %>
      </td>
      <td>
      <%= user.name%>
      </td>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>
  </tbody>
<% end %>
</table>
</div>



</div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>


<div class="container px-5 px-sm-0">
  <div class="row">
  <div class="col-md-3">

  <%= render 'info', user: @user %>
  <%= render 'books/list', book: @book %>
</div>

<div class="col-md-8 offset-md-1">
   <h2>Books</h2>

<table class="table table-hover table-inverse">
 <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
    </thead>

  <tbody>
<% @books.each do |book| %>
    <tr>

      <th>
      <%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
      <% end %>
       </th>

      <td><%= link_to book_path(book.id) do %>
      <%= book.title%>
      <% end %></td>

      <td><%= book.body %></td>
    </tr>
<% end %>
  </tbody>
</table>
</div>



</div>
</div>